version: "3"
services:
  donkey:
    image: robocarstore/donkeycar:latest
    hostname: racer1 # Rename this to Racer2 Racer3 to avoid duplicated names showing in mobile app
    container_name: donkeycar
    ports:
      - "8000:8000"
      - "8887:8887"
    stdin_open: true # docker run -i
    tty: true
    volumes:
      - ./mycar:/root/mycar
    environment:
      - mode=docker
      # - WEB_CONTROL_PORT=18887
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"
      # We need to add this for linux compatibility
      # myconfig.py rely on host.docker.internal to look for simulator running on host
      # https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal

    # network_mode: "host"  # For dev only
